/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'testType' : string,
  'appointmentDate' : string,
  'serialNumber' : string,
  'requestTime' : Time,
}
export interface CustomerPublicView {
  'username' : string,
  'mobileNumber' : string,
}
export interface FeedbackEntry {
  'customerFirstName' : string,
  'feedback' : string,
}
export interface TestResult {
  'cts' : bigint,
  'rns' : bigint,
  'serialNumber2' : string,
  'urineFullExam' : string,
  'hivTests' : bigint,
  'potherTests' : bigint,
  'additionalFieldName' : [] | [string],
  'hepatitisB' : bigint,
  'hepatitisC' : bigint,
  'kbDisc' : string,
  'serialNumber' : string,
  'additionalFieldValue' : [] | [string],
  'platingTests' : bigint,
  'coagulase' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<[string, string, string], undefined>,
  'addCustomer' : ActorMethod<[string, string, string, string], undefined>,
  'addFeedbackEntry' : ActorMethod<[string, string], undefined>,
  'addResetPasscode' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'finalizePasswordReset' : ActorMethod<[string], boolean>,
  'getAllCustomersPublicView' : ActorMethod<[], Array<CustomerPublicView>>,
  'getAllEntries' : ActorMethod<[], Array<FeedbackEntry>>,
  'getAppointments' : ActorMethod<[], Array<AppointmentRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[string], string>,
  'getCustomerCount' : ActorMethod<[], bigint>,
  'getTestResult' : ActorMethod<[string], [] | [TestResult]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestPasswordReset' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContent' : ActorMethod<[string, string], undefined>,
  'updateTestResult' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'verifyResetPasscode' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];