/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerPublicView = IDL.Record({
  'username' : IDL.Text,
  'mobileNumber' : IDL.Text,
});
export const FeedbackEntry = IDL.Record({
  'customerFirstName' : IDL.Text,
  'feedback' : IDL.Text,
});
export const Time = IDL.Int;
export const AppointmentRequest = IDL.Record({
  'testType' : IDL.Text,
  'appointmentDate' : IDL.Text,
  'serialNumber' : IDL.Text,
  'requestTime' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TestResult = IDL.Record({
  'cts' : IDL.Int,
  'rns' : IDL.Int,
  'serialNumber2' : IDL.Text,
  'urineFullExam' : IDL.Text,
  'hivTests' : IDL.Int,
  'potherTests' : IDL.Int,
  'additionalFieldName' : IDL.Opt(IDL.Text),
  'hepatitisB' : IDL.Int,
  'hepatitisC' : IDL.Int,
  'kbDisc' : IDL.Text,
  'serialNumber' : IDL.Text,
  'additionalFieldValue' : IDL.Opt(IDL.Text),
  'platingTests' : IDL.Int,
  'coagulase' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppointment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addFeedbackEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addResetPasscode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'finalizePasswordReset' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllCustomersPublicView' : IDL.Func(
      [],
      [IDL.Vec(CustomerPublicView)],
      ['query'],
    ),
  'getAllEntries' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCustomerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTestResult' : IDL.Func([IDL.Text], [IDL.Opt(TestResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestPasswordReset' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTestResult' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'verifyResetPasscode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerPublicView = IDL.Record({
    'username' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  const FeedbackEntry = IDL.Record({
    'customerFirstName' : IDL.Text,
    'feedback' : IDL.Text,
  });
  const Time = IDL.Int;
  const AppointmentRequest = IDL.Record({
    'testType' : IDL.Text,
    'appointmentDate' : IDL.Text,
    'serialNumber' : IDL.Text,
    'requestTime' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TestResult = IDL.Record({
    'cts' : IDL.Int,
    'rns' : IDL.Int,
    'serialNumber2' : IDL.Text,
    'urineFullExam' : IDL.Text,
    'hivTests' : IDL.Int,
    'potherTests' : IDL.Int,
    'additionalFieldName' : IDL.Opt(IDL.Text),
    'hepatitisB' : IDL.Int,
    'hepatitisC' : IDL.Int,
    'kbDisc' : IDL.Text,
    'serialNumber' : IDL.Text,
    'additionalFieldValue' : IDL.Opt(IDL.Text),
    'platingTests' : IDL.Int,
    'coagulase' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppointment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addFeedbackEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addResetPasscode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'finalizePasswordReset' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllCustomersPublicView' : IDL.Func(
        [],
        [IDL.Vec(CustomerPublicView)],
        ['query'],
      ),
    'getAllEntries' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCustomerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTestResult' : IDL.Func([IDL.Text], [IDL.Opt(TestResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestPasswordReset' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTestResult' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'verifyResetPasscode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };